# mihomo é…ç½®
# æ—¥æœŸï¼š2025-11-08 00:21:37
# é…ç½®ä½œè€…ï¼šhttps://t.me/iKeLee
# é€‚ç”¨ç‰ˆæœ¬ï¼šæ‰€æœ‰ä½¿ç”¨ mihomo æ ¸å¿ƒçš„ç¨‹åº
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true
udp: true

external-controller: 0.0.0.0:9090
# external-ui: ui
# external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'

geox-url:
  # geoip: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat'
  # geosite: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat'
  mmdb: 'https://geodata.kelee.one/Country-Masaiki.mmdb'
  asn: 'https://geodata.kelee.one/GeoLite2-ASN-P3TERX.mmdb'

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com

  skip-domain:
    - Mijia Cloud

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

# P2Pä¸‹è½½ç«¯å£
listeners:
- name: socks5-in-1
  type: socks
  port: 10808
  listen: 0.0.0.0
  udp: true
  users: []
  proxy: DIRECT

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - +.lan
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query

# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…çš„å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…èŠ‚ç‚¹ï¼Œæ¯ 6 ç§’ä¸€æ¬¡å¥åº·æ£€æŸ¥]
#NodeParam: &NodeParam {type: http, interval: 3600, health-check: {enable: true, url: 'http://www.google.com/blank.html', interval: 6}}
NodeParam: &NodeParam {type: http, health-check: {enable: true, url: 'http://www.google.com/blank.html', interval: 3600}}
# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…
proxy-providers: 
#  CornSS:
#    url: ''# ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºè®¢é˜…é“¾æ¥
#    <<: *NodeParam
#    path: './proxy_providers/æœºåœº1.yaml'# ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºè®¢é˜…æ–‡ä»¶å­˜æ”¾åœ°å€
#    override:
#      additional-prefix: "[æœºåœº1] " # ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºåç§°å‰ç¼€

      
# é”šç‚¹ - èŠ‚ç‚¹ç­›é€‰ç»„ ğŸ‡²ğŸ‡´
FilterHK: &FilterHK '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterTW: &FilterTW '^(?=.*((?i)ğŸ‡¹ğŸ‡¼|å°æ¹¾|(\b(TW|Tai|Taiwan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterMO: &FilterMO '^(?=.*((?i)ğŸ‡²ğŸ‡´|æ¾³é—¨|(\b(MO|Macau)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterJP: &FilterJP '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterKR: &FilterKR '^(?=.*((?i)ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ“|é¦–å°”|(\b(KR|Korea)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterSG: &FilterSG '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterUS: &FilterUS '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterUK: &FilterUK '^(?=.*((?i)ğŸ‡¬ğŸ‡§|è‹±å›½|ä¼¦æ•¦|(\b(UK|United Kingdom)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterFR: &FilterFR '^(?=.*((?i)ğŸ‡«ğŸ‡·|æ³•å›½|(\b(FR|France)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterDE: &FilterDE '^(?=.*((?i)ğŸ‡©ğŸ‡ª|å¾·å›½|(\b(DE|Germany)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)\b)|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterGame: &FilterGame '^(?=.*((?i)æ¸¸æˆ|ğŸ®|(\b(GAME|GAMER)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|Ë£Â³|20X|10X|2X|3X|x2)).*$'
FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)ç¾¤|Ë£Â³|20X|10X|2X|3X|x2|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|GAME|GAMER)(\d+)?\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$'

########################åŸå§‹########################
# ç­–ç•¥ç»„å‚æ•°é”šç‚¹
# é”šç‚¹ - æ—¶å»¶ä¼˜é€‰å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œå®¹å·® 20msï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
#UrlTest: &UrlTest {type: url-test, interval: 6, tolerance: 20, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - æ•…éšœè½¬ç§»å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
#FallBack: &FallBack {type: fallback, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è´Ÿè½½å‡è¡¡å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
#LoadBalance: &LoadBalance {type: load-balance, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è§„åˆ™å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…è§„åˆ™ï¼Œæ›´æ–°è§„åˆ™æ—¶ä½¿ç”¨ç›´è¿ç­–ç•¥]
#RuleProviders: &RuleProviders {type: http, behavior: classical, interval: 3600, format: yaml, proxy: DIRECT}


# ç­–ç•¥ç»„å‚æ•°é”šç‚¹
# é”šç‚¹ - æ—¶å»¶ä¼˜é€‰å‚æ•° [æ¯ 3600 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œå®¹å·® 20msï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
UrlTest: &UrlTest {type: url-test, interval: 3600, tolerance: 20, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true,  method: CONNECT}
# é”šç‚¹ - æ•…éšœè½¬ç§»å‚æ•° [æ¯ 3600 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
FallBack: &FallBack {type: fallback, interval: 3600, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true,  method: CONNECT}
# é”šç‚¹ - è´Ÿè½½å‡è¡¡å‚æ•° [æ¯ 3600 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
LoadBalance: &LoadBalance {type: load-balance, interval: 3600, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true,  method: CONNECT}
# é”šç‚¹ - è§„åˆ™å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…è§„åˆ™ï¼Œæ›´æ–°è§„åˆ™æ—¶ä½¿ç”¨ç›´è¿ç­–ç•¥]
RuleProviders: &RuleProviders {type: http, behavior: classical, interval: 3600, format: yaml, proxy: DIRECT}

# ç­–ç•¥ç»„
proxy-groups: 
#  - {name: Game, type: select,  filter: *FilterGame, proxies: [DIRECT, æ¸¸æˆç­–ç•¥]}
#  - {name: Game, type: select, include-all-providers: true, filter: *FilterGame, proxies: [DIRECT, å…¨çƒé€‰æ‹©]}
  - {name: å…¨çƒé€‰æ‹©, type: select, include-all-providers: true, filter: *FilterAll}
#  - {name: å¢ƒå¤–ä¸‹è½½, type: select, include-all-providers: true, filter: *FilterAll, proxies: [DIRECT]}
  - {name: pt, type: select,  proxies: [DIRECT,é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: AI, type: select,  proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: TikTok, type: select,  proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Telegram, type: select,  proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Google, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: PayPal, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: emby, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Netflix, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: YouTube, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Disney, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: HBO, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Hulu, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: PrimeVideo, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: GitHub, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: Steam, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥]}
  - {name: å…œåº•ç­–ç•¥, type: select, proxies: [é¦™æ¸¯ç­–ç•¥, æ¾³é—¨ç­–ç•¥, å°æ¹¾ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, éŸ©å›½ç­–ç•¥, æ–°å›½ç­–ç•¥, ç¾å›½ç­–ç•¥, è‹±å›½ç­–ç•¥, æ³•å›½ç­–ç•¥, å¾·å›½ç­–ç•¥, å…¨çƒç­–ç•¥, DIRECT]}

  - {name: é¦™æ¸¯ç­–ç•¥, type: select, proxies: [â±é¦™æ¸¯æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ¾³é—¨ç­–ç•¥, type: select, proxies: [â±æ¾³é—¨æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ¾³é—¨æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ¾³é—¨è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: å°æ¹¾ç­–ç•¥, type: select, proxies: [â±å°æ¹¾æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ—¥æœ¬ç­–ç•¥, type: select, proxies: [â±æ—¥æœ¬æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: éŸ©å›½ç­–ç•¥, type: select, proxies: [â±éŸ©å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ–°å›½ç­–ç•¥, type: select, proxies: [â±æ–°å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ–°å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ–°å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: ç¾å›½ç­–ç•¥, type: select, proxies: [â±ç¾å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: è‹±å›½ç­–ç•¥, type: select, proxies: [â±è‹±å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥è‹±å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›è‹±å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ³•å›½ç­–ç•¥, type: select, proxies: [â±æ³•å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ³•å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ³•å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: å¾·å›½ç­–ç•¥, type: select, proxies: [â±å¾·å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥å¾·å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›å¾·å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ¸¸æˆç­–ç•¥, type: select, proxies: [â±æ¸¸æˆæ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ¸¸æˆæ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ¸¸æˆè´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: å…¨çƒç­–ç•¥, type: select, proxies: [â±å…¨çƒæ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥å…¨çƒæ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›å…¨çƒè´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}

# æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„
  - {name: â±é¦™æ¸¯æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterHK}
  #- {name: â±é¦™æ¸¯æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, use: [CornSS], filter: *FilterHK}
  - {name: â±æ¾³é—¨æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterMO}
  - {name: â±å°æ¹¾æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterTW}
  - {name: â±æ—¥æœ¬æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterJP}
  - {name: â±éŸ©å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterKR}
  - {name: â±æ–°å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterSG}
  - {name: â±ç¾å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterUS}
  - {name: â±è‹±å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterUK}
  - {name: â±æ³•å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterFR}
  - {name: â±å¾·å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterDE}
  - {name: â±æ¸¸æˆæ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterGame}
  - {name: â±å…¨çƒæ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterAll}

# æ•…éšœè½¬ç§»ç­–ç•¥ç»„
  - {name: ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterHK}
  - {name: ğŸš¥æ¾³é—¨æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterMO}
  - {name: ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterTW}
  - {name: ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterJP}
  - {name: ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterKR}
  - {name: ğŸš¥æ–°å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterSG}
  - {name: ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterUS}
  - {name: ğŸš¥è‹±å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterUK}
  - {name: ğŸš¥æ³•å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterFR}
  - {name: ğŸš¥å¾·å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterDE}
  - {name: ğŸš¥æ¸¸æˆæ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterGame}
  - {name: ğŸš¥å…¨çƒæ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterAll}

# è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
  - {name: ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterHK}
  - {name: ğŸ›æ¾³é—¨è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterMO}
  - {name: ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterTW}
  - {name: ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterJP}
  - {name: ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterKR}
  - {name: ğŸ›æ–°å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterSG}
  - {name: ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterUS}
  - {name: ğŸ›è‹±å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterUK}
  - {name: ğŸ›æ³•å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterFR}
  - {name: ğŸ›å¾·å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterDE}
  - {name: ğŸ›æ¸¸æˆè´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterGame}
  - {name: ğŸ›å…¨çƒè´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterAll}

# è®¢é˜…è§„åˆ™
rule-providers:
  LAN:
    <<: *RuleProviders
    path: './rules/Lan.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/LAN_SPLITTER.yaml'

  Direct:
    <<: *RuleProviders
    path: './rules/Direct.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Direct.yaml'

  pt:
    <<: *RuleProviders
    path: './rules/pt.yaml'
    url: 'https://raw.githubusercontent.com/ioooo0o/rules/refs/heads/main/clash/pt.yaml'

  ChinaDownloadCDN:
    <<: *RuleProviders
    path: './rules/ChinaDownloadCDN.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ChinaDownloadCDN.yaml'

  ChinaMax:
    <<: *RuleProviders
    path: './rules/ChinaMax.yaml'
    url: 'https://rule.kelee.one/Clash/ChinaMax.yaml'

  AI:
    <<: *RuleProviders
    path: './rules/AI.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AI.yaml'

  TikTok:
    <<: *RuleProviders
    path: './rules/TikTok.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/TikTok.yaml'

  Game:
    <<: *RuleProviders
    path: './rules/Game.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Game.yaml'

  emby:
    <<: *RuleProviders
    path: './rules/emby.yaml'
    url: 'https://raw.githubusercontent.com/ioooo0o/rules/refs/heads/main/clash/ziyong.yaml'

  Hulu:
    <<: *RuleProviders
    path: './rules/Hulu.yaml'
    url: 'https://rule.kelee.one/Clash/Hulu.yaml'

  Netflix:
    <<: *RuleProviders
    path: './rules/Netflix.yaml'
    url: 'https://rule.kelee.one/Clash/Netflix.yaml'
    
  Google:
    <<: *RuleProviders
    path: './rules/Google.yaml'
    url: 'https://rule.kelee.one/Clash/Google.yaml'

  YouTube:
    <<: *RuleProviders
    path: './rules/YouTube.yaml'
    url: 'https://rule.kelee.one/Clash/YouTube.yaml'

  Disney:
    <<: *RuleProviders
    path: './rules/Disney.yaml'
    url: 'https://rule.kelee.one/Clash/Disney.yaml'    

  HBO:
    <<: *RuleProviders
    path: './rules/HBO.yaml'
    url: 'https://rule.kelee.one/Clash/HBO.yaml'
  
  PrimeVideo:
    <<: *RuleProviders
    path: './rules/PrimeVideo.yaml'
    url: 'https://rule.kelee.one/Clash/PrimeVideo.yaml'

  GitHub:
    <<: *RuleProviders
    path: './rules/GitHub.yaml'
    url: 'https://rule.kelee.one/Clash/GitHub.yaml'

    
  PayPal:
    <<: *RuleProviders
    path: './rules/PayPal.yaml'
    url: 'https://rule.kelee.one/Clash/PayPal.yaml'

  Steam:
    <<: *RuleProviders
    path: './rules/Steam.yaml'
    url: 'https://rule.kelee.one/Clash/Steam.yaml'


  Telegram:
    <<: *RuleProviders
    path: './rules/Telegram.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Telegram.yaml'

  ESET_China:
    <<: *RuleProviders
    path: './rules/ESET_China.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ESET_China.yaml'

  Proxy:
    <<: *RuleProviders
    path: './rules/Proxy.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Proxy.yaml'

# è§„åˆ™æŒ‡å‘
rules:
  - RULE-SET, LAN, DIRECT 
  - DOMAIN-SUFFIX, nodeseek.com, å…œåº•ç­–ç•¥    
  # steam ä¸‹è½½
  - DOMAIN-SUFFIX, steamserver.net, DIRECT 
  
  - RULE-SET, Direct, DIRECT
  - RULE-SET, pt, pt
  - RULE-SET, ChinaMax, DIRECT  
  - RULE-SET, ChinaDownloadCDN, DIRECT
#  - RULE-SET, InternationalDownloadCDN, å¢ƒå¤–ä¸‹è½½
  - RULE-SET, Google, Google
  - RULE-SET, PayPal, PayPal
  - RULE-SET, AI, AI
  - RULE-SET, TikTok, TikTok
  - RULE-SET, Disney, Disney
#  - RULE-SET, Game, Game
  - RULE-SET, emby, emby
  - RULE-SET, Netflix, Netflix
  - RULE-SET, YouTube, YouTube
  - RULE-SET, HBO, HBO
  - RULE-SET, GitHub, GitHub
  - RULE-SET, Steam, Steam
  - RULE-SET, Hulu, Hulu
  - RULE-SET, PrimeVideo, PrimeVideo
  - RULE-SET, Telegram, Telegram
  - RULE-SET, ESET_China, DIRECT
  - RULE-SET, Proxy, å…œåº•ç­–ç•¥
  - GEOIP, CN, DIRECT
  - MATCH, å…œåº•ç­–ç•¥
